# Generated by Django 5.0.6 on 2025-11-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_copy_data_for_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'can view book'), ('can_create', 'can create book'), ('can_edit', 'can edit book'), ('can_delete', 'can delete book'))},
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
